name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dagger
        run: |
          cd /usr/local
          curl -L https://dl.dagger.io/dagger/install.sh | sh

      - name: Verify secret is available
        env:
          SECRET_MESSAGE: ${{ secrets.SECRET_MESSAGE }}
        run: |
          if [ -z "$SECRET_MESSAGE" ]; then
            echo "❌ SECRET_MESSAGE is not set"
            exit 1
          else
            echo "✅ SECRET_MESSAGE is set"
            echo "Secret value: $SECRET_MESSAGE"
          fi

      - name: Run tests with Dagger
        env:
          SECRET_MESSAGE: ${{ secrets.SECRET_MESSAGE }}
        run: |
          dagger call test --secret-message=env:SECRET_MESSAGE

  # Uncomment this job if you want to publish to a container registry
  # build-and-publish:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.11'
  #
  #     - name: Install Dagger
  #       run: |
  #         cd /usr/local
  #         curl -L https://dl.dagger.io/dagger/install.sh | sh
  #
  #     - name: Publish container
  #       env:
  #         DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
  #         REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  #         REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  #         REGISTRY: ${{ secrets.REGISTRY || 'docker.io/username' }}
  #       run: |
  #         dagger call publish \
  #           --registry="${REGISTRY}" \
  #           --username="${REGISTRY_USERNAME}" \
  #           --password=env:REGISTRY_PASSWORD \
  #           --tag="${GITHUB_SHA:0:7}"